[tool.pymarkdown]
plugins.line-length.code_block_line_length = 88  # Match ruff line-length
plugins.line-length.enabled = true
plugins.line-length.line_length = 120  # Match ruff max-doc-length
plugins.line-length.stern = true
plugins.line-length.tables = false
plugins.no-duplicate-heading.siblings_only = true  # GitHub appends -X for duplicated headings
plugins.no-emphasis-as-heading.enabled = false
plugins.no-inline-html.enabled = false

[tool.tomlsort]
all = true
in_place = true
spaces_before_inline_comment = 2  # Match Python PEP 8
spaces_indent_inline_array = 4  # Match Python PEP 8
trailing_comma_inline_array = true

[tool.typos.default]
extend-ignore-re = ["(?Rm)^.*(#|//)\\s*spellchecker:( )?disable-line$"]

[tool.typos.default.extend-words]
ba = "ba"  # Used in '81ba69'
beed = "beed"  # Used in '9beed7'
darcula = "darcula"

[tool.typos.files]
extend-exclude = [
    "lib/offline.js",
    "lib/reveal-plugins.js",
    "lib/reveal.js",
]
